# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Umay/Desktop/Pong/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Umay/Desktop/Pong/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Umay/Desktop/Pong/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/graph.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/vga.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/scorecond.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/ssgModule.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/anodeSsg.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/clockDivider400Hz.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/clockDivider25MHz.vhd
  C:/Users/Umay/Desktop/Pong/project_1.srcs/sources_1/new/levelCreation.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Umay/Desktop/Pong/project_1.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/Umay/Desktop/Pong/project_1.srcs/constrs_1/new/constraint.xdc]


synth_design -top topModule -part xc7a35tcpg236-1


write_checkpoint -force -noxdef topModule.dcp

catch { report_utilization -file topModule_utilization_synth.rpt -pb topModule_utilization_synth.pb }
